namespace:
  name: prod
 
replicaCount: 2

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

resouces:
  requests:
    CPU: 70m 
    memory: 256Mi

service:
  port: 80
  type: ClusterIP

configMap:
  data: "version: 1.17.0"
  
