namespace:
  name: demo
 
replicaCount: 3

image:
  repository: nginx
  tag: alpine 
  pullPolicy: IfNotPresent

resouces:
  requests:
    CPU: 50m 
    memory: 256Mi

service:
  port: 8111
  type: ClusterIP

configmap:
  data: "version: alpine"
  
