namespace:
  name: staging
 
replicaCount: 1

image:
  repository: nginx
  tag: 1.18.0 
  pullPolicy: IfNotPresent

resouces:
  requests:
    CPU: 50m 
    memory: 128Mi

service:
  port: 8111
  type: ClusterIP

configMap:
  data: "version: 1.18.0"
  
